# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40f88da17b90a083df2fdbd2fac8902e9d6ec4996348cc87c689cb68a9c9ea158499fc4d49c50b50ccca5898e60c165d298fbcfd2e8e224a97bb4423bb66c937

test:
  secret_key_base: c96391065cc7614ae1660363a2af7f3035613a39a981fc75c919826d099e0c4af10bfa538580c3e3bc39241dba703c40f53ed5378fc3234cb056ccdaadcc081a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
